spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://211.178.235.51:3306/BOOKER
    password: haha5032
    jpa:
      hibernate:
        ddl-auto: none
      properties:
        hibernate:
          dialect: com.sparta.booker.domain.search.querydsl.config.MySQL8DialectCustom
          show_sql: false
          format_sql: false
server.port: 8081